kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: my-efs-sc
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-efs-volume
  namespace: my-db
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: [fs-xxxxxxxxxxxxxxxxxxxx]

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-db-mysql-data-disk
  namespace: my-db
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: my-efs-sc
  resources:
    requests:
      storage: 30Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-db-mysql
  namespace: my-db
  labels:
    app: my-db-mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-db-mysql
  template:
    metadata:
      labels:
        app: my-db-mysql
    spec:
      volumes:
        - name: my-db-mysql-data
          persistentVolumeClaim:
            claimName: my-db-mysql-data-disk

      containers:
        - name: my-db-mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "mysql"
              name: my-db-mysql-data
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: database-pwd

---
apiVersion: v1
kind: Service
metadata:
  name: my-db-mysql-service
  namespace: my-db

spec:
  selector:
    app: my-db-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type:  ClusterIP # LadBalancer
